### ISSUE TITLE
IPC calls lose data due to nodejs-mobile-react-native JSON (de)serialization

### ISSUE THREAD

**Issue by achou11** [digidem/comapeo-mobile#392]
Had a situation where from the client, I was calling `mapeoApi.createProject(undefined)` (note the explicit `undefined` argument). Doing that caused me to get an error on the client side:

```sh
 ERROR  [TypeError: Cannot destructure property 'name' of '(intermediate value)(intermediate value)(intermediate value)' as it is null.]
 Error: ENOENT: no such file or directory, open '/data/data/com.comapeo.dev/files/nodejs-builtin_modules/rn-bridge/index.js'
    at Object.readFileSync (node:fs:448:20)
    at getCodeFrame (/Users/andrewchou/GitHub/digidem/comapeo-mobile/node_modules/metro/src/Server.js:868:18)
    at Server._symbolicate (/Users/andrewchou/GitHub/digidem/comapeo-mobile/node_modules/metro/src/Server.js:945:22)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Server._processRequest (/Users/andrewchou/GitHub/digidem/comapeo-mobile/node_modules/metro/src/Server.js:394:7) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/data/data/com.comapeo.dev/files/nodejs-builtin_modules/rn-bridge/index.js'
}
 ```
 
turns out it's because of the combination of our IPC representation and how nodejs-mobile-react-native serializes data over its channels. the IPC represents the call into something like the following:

```sh
{"id": "@@manager", "message": [0, 2, ["createProject"], [undefined]]}
```

and this message gets passed to nodejs-mobile-react-native's `channel.postMessage()`: https://github.com/digidem/comapeo-mobile/blob/8b1917bc02dd57ab8c479865853e7e4492c7c3ed/src/frontend/lib/MessagePortLike.ts#L36

That channel method takes the message and does a simple `JSON.stringify()` on it, which is where the issue lies. Stringifying that message turns into the following:

```js
'{"id":"@@manager","message":[0,2,["createProject"],[null]]}'
```

Note how that `[undefined]` has now become `[null]`! This seems to be the default behavior of JSON stringification so when it gets parsed and passed along to eventually call the associated server-side code, we're calling `mapeoApi.createProject(null)`, which causes the error seems in the error message above.

big thanks to @EvanHahn who helped figure this out with me. not really sure what the best solution is, but there are a couple of ideas that we came up with that both don't seem great (but maybe fine in the short term).

**Comment by achou11** [comment]
Another tangential item: we should really improve the error messages so that there's some semblance of a stack trace. Spent way too much time getting distracted by the ENOENT error, which was a red herring

**Comment by gmaclennan** [comment]
I think this is an issue for rpc-reflector. rpc-reflector should encode function arguments in a way that can be stringified as JSON, because of how common JSON is as an encoding format, and because it's what we use.

**Comment by gmaclennan** [comment]
https://github.com/digidem/rpc-reflector/issues/21

**Comment by gmaclennan** [comment]
I have a feeling the error handling might be for rpc-reflector too - the first line of your error is the actual error from `createProject()`, which is serialized over IPC by rpc-reflector. It seems like the error stack is what is incorrect, I'm not sure why.

**Comment by gmaclennan** [comment]
The error beyond the first line you are seeing I think it actually because metro is attempting to "symbolicate" the error message, and it is seeing rn-bridge in the stack (because it's being serialized and passed from backend to frontend) and then metro is error-ing when trying to symbolicate the actual stack. We need to figure out how to stop metro from trying to do this.

**Comment by ErikSin** [comment]
Has this been fixed? Can I close this issue?
